# Generated by Django 2.1 on 2018-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Misurazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunghezza', models.IntegerField(default=0)),
                ('misurazione1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('misurazione2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('misurazione3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('misurazione4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('misurazione5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('media', models.IntegerField(default=0)),
                ('errore', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
