# Generated by Django 2.1 on 2018-11-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misurazione',
            name='misurazione4',
        ),
        migrations.RemoveField(
            model_name='misurazione',
            name='misurazione5',
        ),
    ]
