# Generated by Django 2.1 on 2018-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisica', '0002_auto_20181117_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misurazione',
            name='errore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='misurazione',
            name='media',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
